routes:
  - name: api_mecadolibre_com
    originIps:
    - '::ffff:127.0.0.1'
    path: /someroute/categories
    pathTransform: 
      basepath: /someroute
      replaceTo: /
    methods: 
      - get
      - post
    routeTo: 
      protocol: https
      host: api.mercadolibre.com
  - name: meli_api
    path: /meli-api
    hosts: 
      - localhost
      - my.host.local
    methods: 
      - get
      - put
      - patch
      - options
    routeTo:
      protocol: https
      host: 61eff8e2732d93001778e768.mockapi.io
    pathTransform:
      basepath: /meli-api
      rep`laceTo: /api
